// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAMSZPl_xPS0pnma2ijNM8e-m2QJjRe70',
    appId: '1:657041835280:web:7b6ab2288beff6f58f9195',
    messagingSenderId: '657041835280',
    projectId: 'chat-app-48d16',
    authDomain: 'chat-app-48d16.firebaseapp.com',
    storageBucket: 'chat-app-48d16.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKcscaKBxaz4TN0IAr--ooIb8wCDwPwEQ',
    appId: '1:657041835280:android:740111f46f3f7b5e8f9195',
    messagingSenderId: '657041835280',
    projectId: 'chat-app-48d16',
    storageBucket: 'chat-app-48d16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLaFScPH6BSSH63vNvylYAN6F1Q_BkAIQ',
    appId: '1:657041835280:ios:68d8b0e099b883488f9195',
    messagingSenderId: '657041835280',
    projectId: 'chat-app-48d16',
    storageBucket: 'chat-app-48d16.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLaFScPH6BSSH63vNvylYAN6F1Q_BkAIQ',
    appId: '1:657041835280:ios:68d8b0e099b883488f9195',
    messagingSenderId: '657041835280',
    projectId: 'chat-app-48d16',
    storageBucket: 'chat-app-48d16.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAMSZPl_xPS0pnma2ijNM8e-m2QJjRe70',
    appId: '1:657041835280:web:0adc7fa8094df29c8f9195',
    messagingSenderId: '657041835280',
    projectId: 'chat-app-48d16',
    authDomain: 'chat-app-48d16.firebaseapp.com',
    storageBucket: 'chat-app-48d16.appspot.com',
  );
}
